In [1]:
import pandas as pd
import numpy as np
from sklearn.pipeline import make_pipeline
from skrebate import ReliefF
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [2]:
genetic_data = pd.read_csv('https://github.com/EpistasisLab/scikit-rebate/raw/master/data/'
                           'GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1.tsv.gz',
                           sep='\t', compression='gzip')

In [3]:
genetic_data.head(10)

,N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,...,N11,N12,N13,N14,N15,N16,N17,P1,P2,class
0,0,0,2,1,1,0,0,2,0,1,...,2,1,0,0,0,0,0,0,1,1
1,0,0,1,0,0,1,1,0,0,1,...,0,1,0,0,0,0,0,0,0,1
2,0,0,0,1,0,2,0,0,0,0,...,1,1,0,0,2,2,0,0,0,1
3,0,1,0,2,0,1,0,2,0,0,...,1,1,0,1,1,0,1,1,0,1
4,0,0,1,1,0,0,0,1,1,0,...,1,0,0,1,0,0,1,1,0,1
5,0,0,0,1,1,1,1,1,0,2,...,1,0,0,0,1,0,0,1,0,1
6,0,0,0,1,1,2,2,0,1,0,...,2,0,0,1,1,0,1,1,0,1
7,0,1,1,0,1,0,1,0,0,0,...,1,0,0,0,0,1,0,1,0,1
8,0,0,1,1,0,1,1,2,0,2,...,0,1,0,0,0,0,2,0,1,1
9,0,1,2,1,0,1,1,1,0,2,...,0,0,0,1,0,0,1,1,0,1

In [8]:
features, labels=genetic_data.drop('class', axis=1).values, genetic_data['class'].values

In [11]:
clf = make_pipeline(ReliefF(n_features_to_select=2, n_neighbors=100),
                    RandomForestClassifier(n_estimators=100))

In [13]:
print(np.mean(cross_val_score(clf, features, labels)))

0.7931250000000001